"""empty message

Revision ID: 419ae9d5faa8
Revises: 9e552b446639
Create Date: 2022-01-27 16:21:50.298217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419ae9d5faa8'
down_revision = '9e552b446639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('remodel_item_tool_instruction_id_fkey', 'remodel_item', type_='foreignkey')
    op.drop_column('remodel_item', 'tool_instruction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remodel_item', sa.Column('tool_instruction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('remodel_item_tool_instruction_id_fkey', 'remodel_item', 'tool_instruction', ['tool_instruction_id'], ['tool_instruction_id'])
    # ### end Alembic commands ###
