"""empty message

Revision ID: 63c05ae7522e
Revises: b03e36ed450f
Create Date: 2022-01-27 12:55:01.976174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c05ae7522e'
down_revision = 'b03e36ed450f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('remodel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room', 'remodel_item', ['remodel_id'], ['remodel_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'remodel_id')
    # ### end Alembic commands ###
