"""empty message

Revision ID: 9e552b446639
Revises: 63c05ae7522e
Create Date: 2022-01-27 12:58:59.246211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e552b446639'
down_revision = '63c05ae7522e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remodel_item', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'remodel_item', 'room', ['room_id'], ['room_id'])
    op.drop_constraint('room_remodel_id_fkey', 'room', type_='foreignkey')
    op.drop_column('room', 'remodel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('remodel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('room_remodel_id_fkey', 'room', 'remodel_item', ['remodel_id'], ['remodel_id'])
    op.drop_constraint(None, 'remodel_item', type_='foreignkey')
    op.drop_column('remodel_item', 'room_id')
    # ### end Alembic commands ###
