"""empty message

Revision ID: b03e36ed450f
Revises: 
Create Date: 2022-01-26 17:43:26.250602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03e36ed450f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruction',
    sa.Column('instruction_id', sa.Integer(), nullable=False),
    sa.Column('instruction_name', sa.String(), nullable=True),
    sa.Column('instruction_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('instruction_id')
    )
    op.create_index(op.f('ix_instruction_instruction_name'), 'instruction', ['instruction_name'], unique=False)
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_room_room_name'), 'room', ['room_name'], unique=False)
    op.create_table('tool_instruction',
    sa.Column('tool_instruction_id', sa.Integer(), nullable=False),
    sa.Column('tool_instruction_name', sa.String(), nullable=True),
    sa.Column('tool_instruction_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tool_instruction_id')
    )
    op.create_index(op.f('ix_tool_instruction_tool_instruction_name'), 'tool_instruction', ['tool_instruction_name'], unique=False)
    op.create_table('tool',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('avg_price', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_image', sa.String(), nullable=True),
    sa.Column('tool_instruction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tool_instruction_id'], ['tool_instruction.tool_instruction_id'], ),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_index(op.f('ix_tool_tool_name'), 'tool', ['tool_name'], unique=False)
    op.create_table('remodel_item',
    sa.Column('remodel_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('instruction_id', sa.Integer(), nullable=True),
    sa.Column('tool_instruction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instruction_id'], ['instruction.instruction_id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.tool_id'], ),
    sa.ForeignKeyConstraint(['tool_instruction_id'], ['tool_instruction.tool_instruction_id'], ),
    sa.PrimaryKeyConstraint('remodel_id')
    )
    op.create_index(op.f('ix_remodel_item_item_name'), 'remodel_item', ['item_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remodel_item_item_name'), table_name='remodel_item')
    op.drop_table('remodel_item')
    op.drop_index(op.f('ix_tool_tool_name'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_tool_instruction_tool_instruction_name'), table_name='tool_instruction')
    op.drop_table('tool_instruction')
    op.drop_index(op.f('ix_room_room_name'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_instruction_instruction_name'), table_name='instruction')
    op.drop_table('instruction')
    # ### end Alembic commands ###
